### PR TITLE
added Product Model

### PR DESCRIPTION
**Pull request by Daniel-Brewer**
# Description

For dependency functionality I've added the Product Model

## Type of change

Added Product Model

# Testing Instructions for Change Made

git fetch --all
git checkout db-product
verify that Product.cs exists in the Models Folder

### CODE REVIEW

**Comment by ColleenWoolsey** [comment]
Found Product.cs in Models Folder and code looks good

**Review by ColleenWoolsey — APPROVED** [review]

**Review by dakotacookson — APPROVED** [review]
looks good

**Review by zwcrawford — APPROVED** [review]
Product Class looks good

**Review by askingalot — CHANGES_REQUESTED** [review]
I think you might want to put some validation attributes on the properties in the Product model.

**Review by askingalot — APPROVED** [review]

**Pull request merged**
